pool:
  name: Azure Pipelines
steps:
- task: CopyFiles@2
  displayName: '$(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: test
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Helpfiles'

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: specific
    project: '361c4cf4-d0b3-4558-b09f-f223869b49a7'
    pipeline: 9
    downloadType: specific
    downloadPath: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Updater'
  inputs:
    ArtifactName: Updater

